version: '3.1'

services:
  springboot:
    image: dockerhandson/spring-boot-mongo:IMAGETAG
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
    - springappnetwork  

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    
networks:
  springappnetwork:
